include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - public_member_api_docs
    - unawaited_futures
    - prefer_const_constructors
    - always_declare_return_types
    - avoid_dynamic_calls
