name: CI

on:
  push:
    branches: [main, dev, new]
  pull_request:

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Format
        run: dart format --output=none --set-exit-if-changed .
      - name: Test plugin
        run: flutter test
      - name: Install example dependencies
        run: flutter pub get
        working-directory: example
      - name: Test example
        run: flutter test
        working-directory: example

  publish-dry-run:
    runs-on: ubuntu-latest
    needs: dart
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Pub publish dry-run
        run: dart pub publish --dry-run
