name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: k-paxian/dart-package-publisher@v1.6
    # with:
    #   working-directory: path/to/package/within/repository
